apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 3
  selector:
    app: iisrc 
  template:
    metadata:
      name: iisname1
      labels:
        app: iisrc
    spec:
      containers:
      - name: container
        image: microsoft/iis
        ports:
        - containerPort: 80
