apiVersion: v1
kind: Pod
metadata:
  name: my-empty-dir
  labels:
    app: empty-dir
spec:
  containers:
  - image: microsoft/iis 
    name: test-container-1

    command: [ 'powershell', '-c', 'echo Running alpine container 1; sleep 3600']

    volumeMounts:
    - mountPath: C:/cache1
      name: cache-volume

  - image: microsoft/iis
    name: test-container-2

    command: ['powershell', '-c', 'echo Running container 2; sleep 3600']

    volumeMounts:
    - mountPath: C:/cache2
      name: cache-volume

  volumes:
  - name: cache-volume
    emptyDir: {}
