ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Docker EE Master Server
  config.vm.define "docker1" do |docker1|
    docker1.vm.box = "centos/7"
    docker1.vm.hostname = "docker1"
    docker1.vm.network "private_network", ip: "192.168.76.137"
	docker1.vm.disk :disk, size: "20GB", primary: true
    docker1.vm.provider "virtualbox" do |v|
      v.name = "docker1"
      v.memory = 4000
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    docker1.vm.provision "shell", path: "bootstrap_dockereemaster.sh"
  end
 end